"""Recover only an interrupted, unoptimized first batch of real policy draws."""
from __future__ import annotations

import hashlib
import json
from collections import defaultdict
from functools import lru_cache
from pathlib import Path

from verl.experimental.error_span_opd.replay import (
    _Corpus, RecordedClient, ReplayError, _ids, _plain, _sample_id,
)
from verl.experimental.error_span_opd.worker import ErrorSpanAgentLoop


@lru_cache(maxsize=2)
def verified_corpus(source: str, source_sha256: str, student: str, data_files: tuple[str, ...]):
    # A loop object is constructed per trajectory. Validate/load the immutable
    # source once per worker process, rather than rereading it for every draw.
    corpus = _Corpus(source, expected_run_kind="formal", expected_validation_rows=600)
    if corpus.source_hash != source_sha256:
        raise ReplayError("initial recovery source hash differs from frozen configuration")
    recorded = corpus.launch["models"]["student"]
    if recorded["path"] != student:
        raise ReplayError("initial recovery student model path differs")
    for name, metadata in recorded["files"].items():
        file = Path(student) / name
        stat = file.stat()
        if stat.st_size != metadata["size"] or stat.st_mtime_ns != metadata["mtime_ns"]:
            raise ReplayError(f"initial recovery model file changed: {name}")
        if "sha256" in metadata and hashlib.sha256(file.read_bytes()).hexdigest() != metadata["sha256"]:
            raise ReplayError(f"initial recovery model metadata changed: {name}")
    current_data = {str(Path(p).resolve()): hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in data_files}
    if current_data != corpus.launch["data_sha256"]:
        raise ReplayError("initial recovery data manifests differ from source run")
    groups = defaultdict(list)
    for (_sid, validate, _seed), record in corpus.records.items():
        if validate:
            continue
        groups[record["sample_id"]].append(record)
        for phase in record["phases"]:
            version = phase.get("server_extra_fields", {})
            if any(version.get(key) != 0 for key in ("global_steps", "min_global_steps", "max_global_steps")):
                raise ReplayError("recovery source was not generated by initial policy")
    if len(groups) != 32 or any(sorted(r["rollout_index"] for r in rows) != [0, 1, 2, 3] for rows in groups.values()):
        raise ReplayError("initial recovery requires exactly 32 questions with all four assigned draws")
    return corpus


class InitialBatchRecoveryAgentLoop(ErrorSpanAgentLoop):
    """Reuse initial policy draws at step 1; all other calls use the live model."""

    def __init__(self, *args, recovery_source: str, recovery_source_sha256: str, **kwargs):
        super().__init__(*args, **kwargs)
        if self.config.error_span_opd.run_kind != "formal" or self.config.trainer.resume_mode != "disable":
            raise ReplayError("initial-batch recovery requires a fresh formal trainer from initial weights")
        self.recovery_source = str(Path(recovery_source).resolve())
        self.recovery_source_sha256 = recovery_source_sha256
        self.recovery_student = str(self.config.actor_rollout_ref.model.path)
        self.recovery_data_files = tuple(str(p) for p in [*self.config.data.train_files, *self.config.data.val_files])

    async def run(
        self, sampling_params, validate=False, *, error_span_step=None, error_span_validate=None, **kwargs
    ):
        if error_span_step is None or error_span_validate is None:
            raise ReplayError("initial recovery requires explicit trainer step and validation metadata")
        step = int(error_span_step)
        if bool(validate) != bool(error_span_validate):
            raise ReplayError("initial recovery validation metadata disagrees with trainer")
        if step < 0 or (not validate and step < 1):
            raise ReplayError("initial recovery received an invalid trainer step")
        if validate or step >= 2:
            output = await super().run(sampling_params, validate=validate, **kwargs)
            output.extra_fields["initial_batch_recovery"] = {"recovered": False, "step": step, "live_backend": True}
            return output

        corpus = verified_corpus(
            self.recovery_source, self.recovery_source_sha256, self.recovery_student, self.recovery_data_files
        )
        sid = _sample_id(kwargs)
        seed = sampling_params.get("seed")
        if seed is None:
            raise ReplayError("initial recovery training request has no seed")
        record = corpus.records.get((sid or "", False, int(seed)))
        if record is None:
            raise ReplayError(f"initial recovery has no assigned draw for {sid!r} seed={seed}")
        extra = _plain(kwargs.get("extra_info", {}))
        for key in ("image_id", "image_path", "expression"):
            if extra.get(key) != record[key]:
                raise ReplayError(f"initial recovery {key} differs from original draw")
        if extra.get("target_bbox_normalized") != record["ground_truth_bbox"]:
            raise ReplayError("initial recovery GT differs from original draw")

        client = RecordedClient(self.server_manager, corpus, sid, False)
        original_client = self.server_manager
        self.server_manager = client
        try:
            # The native loop builds the exact real prompt and staged token
            # composition; RecordedClient checks every prompt/seed/budget.
            output = await super().run(sampling_params, validate=False, **kwargs)
        finally:
            self.server_manager = original_client
        if client.fallback or client.record is None or client.phase_index != len(record["phases"]):
            raise ReplayError("initial recovery did not consume exactly the recorded draw")
        if _ids(output.prompt_ids, "prompt") != record["prompt"] or _ids(output.response_ids, "response") != record["response"]:
            raise ReplayError("initial recovery changed original prompt or response tokens")
        provenance = dict(client.provenance(), recovered=True, step=step, live_backend=False)
        output.extra_fields["initial_batch_recovery"] = provenance
        receipt = output.extra_fields.get("routed_grounding_receipt")
        if receipt is not None:
            receipt["initial_batch_recovery"] = provenance
        return output


@lru_cache(maxsize=2)
def verified_interrupted_corpus(
    source: str,
    source_sha256: str,
    student: str,
    data_files: tuple[str, ...],
    recovered_steps: int,
):
    """Validate a multi-step corpus before reconstructing an interrupted run."""

    if recovered_steps <= 0:
        raise ReplayError("interrupted recovery requires at least one completed update")
    corpus = _Corpus(
        source,
        expected_run_kind="pilot",
        expected_training_rows=128 * recovered_steps,
        expected_validation_rows=600,
        expected_training_steps=tuple(range(1, recovered_steps + 1)),
        allow_update_evidence=True,
    )
    if corpus.source_hash != source_sha256:
        raise ReplayError("interrupted recovery source hash differs from frozen configuration")
    recorded = corpus.launch["models"]["student"]
    if recorded["path"] != student:
        raise ReplayError("interrupted recovery student model path differs")
    current_data = {
        str(Path(path).resolve()): hashlib.sha256(Path(path).read_bytes()).hexdigest()
        for path in data_files
    }
    if current_data != corpus.launch["data_sha256"]:
        raise ReplayError("interrupted recovery data manifests differ from source run")

    ledger_path = corpus.source / "span_steps.jsonl"
    ledger = [json.loads(line) for line in ledger_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if [int(row.get("step", -1)) for row in ledger] != list(range(1, recovered_steps + 1)):
        raise ReplayError("interrupted recovery ledger is not a complete ordered prefix")
    for row in ledger:
        if row.get("arm") != "ROSD" or int(row.get("error_span/assigned_trajectories", -1)) != 128:
            raise ReplayError("interrupted recovery ledger does not describe complete ROSD batches")
        if int(row.get("error_span/selected_trajectories", 0)) <= 0:
            raise ReplayError("interrupted recovery ledger contains an empty optimizer batch")

    groups = defaultdict(list)
    for (_sid, validate, _seed), record in corpus.records.items():
        if validate:
            continue
        step = int(record["step"])
        groups[(step, record["sample_id"])].append(record)
        expected_version = step - 1
        for phase in record["phases"]:
            version = phase.get("server_extra_fields", {})
            if any(
                version.get(key) != expected_version
                for key in ("global_steps", "min_global_steps", "max_global_steps")
            ):
                raise ReplayError("interrupted recovery source has a stale policy version")
    for step in range(1, recovered_steps + 1):
        step_groups = [rows for (group_step, _sid), rows in groups.items() if group_step == step]
        if len(step_groups) != 32 or any(
            sorted(int(record["rollout_index"]) for record in rows) != [0, 1, 2, 3]
            for rows in step_groups
        ):
            raise ReplayError(f"interrupted recovery step {step} lacks 32 complete rollout groups")
    return corpus


class InterruptedRunRecoveryAgentLoop(ErrorSpanAgentLoop):
    """Replay a completed update prefix, then return to the live on-policy backend."""

    def __init__(
        self,
        *args,
        recovery_source: str,
        recovery_source_sha256: str,
        recovered_steps: int,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        if self.config.error_span_opd.run_kind != "pilot_recovery" or self.config.trainer.resume_mode != "disable":
            raise ReplayError("interrupted-run recovery requires run_kind=pilot_recovery and a fresh trainer")
        self.recovery_source = str(Path(recovery_source).resolve())
        self.recovery_source_sha256 = str(recovery_source_sha256)
        self.recovered_steps = int(recovered_steps)
        if not 0 < self.recovered_steps < int(self.config.trainer.total_training_steps):
            raise ReplayError("recovered_steps must be a strict prefix of total_training_steps")
        self.recovery_student = str(self.config.actor_rollout_ref.model.path)
        self.recovery_data_files = tuple(
            str(path) for path in [*self.config.data.train_files, *self.config.data.val_files]
        )

    async def run(
        self,
        sampling_params,
        validate=False,
        *,
        error_span_step=None,
        error_span_validate=None,
        **kwargs,
    ):
        if error_span_step is None or error_span_validate is None:
            raise ReplayError("interrupted recovery requires explicit trainer step and validation metadata")
        step = int(error_span_step)
        if bool(validate) != bool(error_span_validate):
            raise ReplayError("interrupted recovery validation metadata disagrees with trainer")
        if validate or step > self.recovered_steps:
            output = await super().run(sampling_params, validate=validate, **kwargs)
            output.extra_fields["interrupted_run_recovery"] = {
                "recovered": False,
                "step": step,
                "live_backend": True,
            }
            return output

        corpus = verified_interrupted_corpus(
            self.recovery_source,
            self.recovery_source_sha256,
            self.recovery_student,
            self.recovery_data_files,
            self.recovered_steps,
        )
        sid = _sample_id(kwargs)
        seed = sampling_params.get("seed")
        if seed is None:
            raise ReplayError("interrupted recovery training request has no seed")
        record = corpus.records.get((sid or "", False, int(seed)))
        if record is None or int(record["step"]) != step:
            raise ReplayError(f"interrupted recovery has no step-{step} draw for {sid!r} seed={seed}")
        extra = _plain(kwargs.get("extra_info", {}))
        for key in ("image_id", "image_path", "expression"):
            if extra.get(key) != record[key]:
                raise ReplayError(f"interrupted recovery {key} differs from original draw")
        if extra.get("target_bbox_normalized") != record["ground_truth_bbox"]:
            raise ReplayError("interrupted recovery GT differs from original draw")

        client = RecordedClient(self.server_manager, corpus, sid, False)
        original_client = self.server_manager
        self.server_manager = client
        try:
            output = await super().run(sampling_params, validate=False, **kwargs)
        finally:
            self.server_manager = original_client
        if client.fallback or client.record is None or client.phase_index != len(record["phases"]):
            raise ReplayError("interrupted recovery did not consume exactly the recorded draw")
        if _ids(output.prompt_ids, "prompt") != record["prompt"] or _ids(
            output.response_ids, "response"
        ) != record["response"]:
            raise ReplayError("interrupted recovery changed original prompt or response tokens")
        provenance = dict(client.provenance(), recovered=True, step=step, live_backend=False)
        output.extra_fields["interrupted_run_recovery"] = provenance
        receipt = output.extra_fields.get("routed_grounding_receipt")
        if receipt is not None:
            receipt["interrupted_run_recovery"] = provenance
        return output
